"""empty message

Revision ID: 7d0c6d8ef51e
Revises: 6c6a7695da8b
Create Date: 2023-02-10 17:49:12.333305

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d0c6d8ef51e'
down_revision = '6c6a7695da8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
